<HTML>
<BODY BGCOLOR="white">
<PRE>
<FONT color="green">001</FONT>    package org.junit.rules;<a name="line.1"></a>
<FONT color="green">002</FONT>    <a name="line.2"></a>
<FONT color="green">003</FONT>    import static org.junit.Assert.assertThat;<a name="line.3"></a>
<FONT color="green">004</FONT>    <a name="line.4"></a>
<FONT color="green">005</FONT>    import java.util.ArrayList;<a name="line.5"></a>
<FONT color="green">006</FONT>    import java.util.List;<a name="line.6"></a>
<FONT color="green">007</FONT>    import java.util.concurrent.Callable;<a name="line.7"></a>
<FONT color="green">008</FONT>    <a name="line.8"></a>
<FONT color="green">009</FONT>    import org.hamcrest.Matcher;<a name="line.9"></a>
<FONT color="green">010</FONT>    import org.junit.runners.model.MultipleFailureException;<a name="line.10"></a>
<FONT color="green">011</FONT>    <a name="line.11"></a>
<FONT color="green">012</FONT>    /**<a name="line.12"></a>
<FONT color="green">013</FONT>     * The ErrorCollector rule allows execution of a test to continue after the<a name="line.13"></a>
<FONT color="green">014</FONT>     * first problem is found (for example, to collect _all_ the incorrect rows in a<a name="line.14"></a>
<FONT color="green">015</FONT>     * table, and report them all at once):<a name="line.15"></a>
<FONT color="green">016</FONT>     *<a name="line.16"></a>
<FONT color="green">017</FONT>     * &lt;pre&gt;<a name="line.17"></a>
<FONT color="green">018</FONT>     * public static class UsesErrorCollectorTwice {<a name="line.18"></a>
<FONT color="green">019</FONT>     *      &amp;#064;Rule<a name="line.19"></a>
<FONT color="green">020</FONT>     *      public ErrorCollector collector= new ErrorCollector();<a name="line.20"></a>
<FONT color="green">021</FONT>     *<a name="line.21"></a>
<FONT color="green">022</FONT>     * &amp;#064;Test<a name="line.22"></a>
<FONT color="green">023</FONT>     * public void example() {<a name="line.23"></a>
<FONT color="green">024</FONT>     *      collector.addError(new Throwable(&amp;quot;first thing went wrong&amp;quot;));<a name="line.24"></a>
<FONT color="green">025</FONT>     *      collector.addError(new Throwable(&amp;quot;second thing went wrong&amp;quot;));<a name="line.25"></a>
<FONT color="green">026</FONT>     *      collector.checkThat(getResult(), not(containsString(&amp;quot;ERROR!&amp;quot;)));<a name="line.26"></a>
<FONT color="green">027</FONT>     *      // all lines will run, and then a combined failure logged at the end.<a name="line.27"></a>
<FONT color="green">028</FONT>     *     }<a name="line.28"></a>
<FONT color="green">029</FONT>     * }<a name="line.29"></a>
<FONT color="green">030</FONT>     * &lt;/pre&gt;<a name="line.30"></a>
<FONT color="green">031</FONT>     *<a name="line.31"></a>
<FONT color="green">032</FONT>     * @since 4.7<a name="line.32"></a>
<FONT color="green">033</FONT>     */<a name="line.33"></a>
<FONT color="green">034</FONT>    public class ErrorCollector extends Verifier {<a name="line.34"></a>
<FONT color="green">035</FONT>        private List&lt;Throwable&gt; errors = new ArrayList&lt;Throwable&gt;();<a name="line.35"></a>
<FONT color="green">036</FONT>    <a name="line.36"></a>
<FONT color="green">037</FONT>        @Override<a name="line.37"></a>
<FONT color="green">038</FONT>        protected void verify() throws Throwable {<a name="line.38"></a>
<FONT color="green">039</FONT>            MultipleFailureException.assertEmpty(errors);<a name="line.39"></a>
<FONT color="green">040</FONT>        }<a name="line.40"></a>
<FONT color="green">041</FONT>    <a name="line.41"></a>
<FONT color="green">042</FONT>        /**<a name="line.42"></a>
<FONT color="green">043</FONT>         * Adds a Throwable to the table.  Execution continues, but the test will fail at the end.<a name="line.43"></a>
<FONT color="green">044</FONT>         */<a name="line.44"></a>
<FONT color="green">045</FONT>        public void addError(Throwable error) {<a name="line.45"></a>
<FONT color="green">046</FONT>            errors.add(error);<a name="line.46"></a>
<FONT color="green">047</FONT>        }<a name="line.47"></a>
<FONT color="green">048</FONT>    <a name="line.48"></a>
<FONT color="green">049</FONT>        /**<a name="line.49"></a>
<FONT color="green">050</FONT>         * Adds a failure to the table if {@code matcher} does not match {@code value}.<a name="line.50"></a>
<FONT color="green">051</FONT>         * Execution continues, but the test will fail at the end if the match fails.<a name="line.51"></a>
<FONT color="green">052</FONT>         */<a name="line.52"></a>
<FONT color="green">053</FONT>        public &lt;T&gt; void checkThat(final T value, final Matcher&lt;T&gt; matcher) {<a name="line.53"></a>
<FONT color="green">054</FONT>            checkThat("", value, matcher);<a name="line.54"></a>
<FONT color="green">055</FONT>        }<a name="line.55"></a>
<FONT color="green">056</FONT>    <a name="line.56"></a>
<FONT color="green">057</FONT>        /**<a name="line.57"></a>
<FONT color="green">058</FONT>         * Adds a failure with the given {@code reason}<a name="line.58"></a>
<FONT color="green">059</FONT>         * to the table if {@code matcher} does not match {@code value}.<a name="line.59"></a>
<FONT color="green">060</FONT>         * Execution continues, but the test will fail at the end if the match fails.<a name="line.60"></a>
<FONT color="green">061</FONT>         */<a name="line.61"></a>
<FONT color="green">062</FONT>        public &lt;T&gt; void checkThat(final String reason, final T value, final Matcher&lt;T&gt; matcher) {<a name="line.62"></a>
<FONT color="green">063</FONT>            checkSucceeds(new Callable&lt;Object&gt;() {<a name="line.63"></a>
<FONT color="green">064</FONT>                public Object call() throws Exception {<a name="line.64"></a>
<FONT color="green">065</FONT>                    assertThat(reason, value, matcher);<a name="line.65"></a>
<FONT color="green">066</FONT>                    return value;<a name="line.66"></a>
<FONT color="green">067</FONT>                }<a name="line.67"></a>
<FONT color="green">068</FONT>            });<a name="line.68"></a>
<FONT color="green">069</FONT>        }<a name="line.69"></a>
<FONT color="green">070</FONT>    <a name="line.70"></a>
<FONT color="green">071</FONT>        /**<a name="line.71"></a>
<FONT color="green">072</FONT>         * Adds to the table the exception, if any, thrown from {@code callable}.<a name="line.72"></a>
<FONT color="green">073</FONT>         * Execution continues, but the test will fail at the end if<a name="line.73"></a>
<FONT color="green">074</FONT>         * {@code callable} threw an exception.<a name="line.74"></a>
<FONT color="green">075</FONT>         */<a name="line.75"></a>
<FONT color="green">076</FONT>        public &lt;T&gt; T checkSucceeds(Callable&lt;T&gt; callable) {<a name="line.76"></a>
<FONT color="green">077</FONT>            try {<a name="line.77"></a>
<FONT color="green">078</FONT>                return callable.call();<a name="line.78"></a>
<FONT color="green">079</FONT>            } catch (Throwable e) {<a name="line.79"></a>
<FONT color="green">080</FONT>                addError(e);<a name="line.80"></a>
<FONT color="green">081</FONT>                return null;<a name="line.81"></a>
<FONT color="green">082</FONT>            }<a name="line.82"></a>
<FONT color="green">083</FONT>        }<a name="line.83"></a>
<FONT color="green">084</FONT>    }<a name="line.84"></a>




























































</PRE>
</BODY>
</HTML>
